### ISSUE TITLE
Controller logs resource conflict error messages

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#131]
{"level":"error","ts":"2021-03-19T15:34:29.949Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","error":"Operation cannot be fulfilled on imageupdateautomations.image.toolkit.fluxcd.io \"flux-system\": the object has been modified; please apply your changes to the latest version and try again"}

The line at which this problem arises is https://github.com/fluxcd/image-automation-controller/blob/main/controllers/imageupdateautomation_controller.go#L263.

**Comment by bigkevmcd** [comment]
I've got a fix lined up for this, if I can work out a test

**Comment by stefanprodan** [comment]
More users are hitting this: https://cloud-native.slack.com/archives/CLAJ40HV3/p1616283160302500?thread_ts=1616279639.295100&cid=CLAJ40HV3
