### ISSUE TITLE
Release image/v1alpha2

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#150]
`image.toolkit.fluxcd.io/v1alpha2` includes breaking changes from `v1alpha1`, so needs some careful handling.

 - bump the version in image-reflector-controller -- even though nothing changes for that part of the API, it means not keeping two separate versions around, and the complication that entails.
 - remove v1alpha1 from CRDs, otherwise Kubernetes will think it should try to transform v1alpha1 resources into v1alpha2, and fail
 - migration: when you install the new version, any image/v1alpha1 YAMLs will fail to sync until you update them. Can we do better than that?

**Comment by stefanprodan** [comment]
Can this be closed? We shipped v1alpha2 some weeks ago

**Comment by squaremo** [comment]
> Can this be closed? We shipped v1alpha2 some weeks ago

Did the things in the description happen? I wasn't here ...

**Comment by squaremo** [comment]
> We ended up with a different solution, both versions were delivered

OK I see, the solution is to let it try to up-convert, and fail on the missing field -- fair enough, that's practical.

In that case, yes we've moved past this bug :-)
