### ISSUE TITLE
ImagePolicy not compatible with Flux v1 behaviour

### ISSUE THREAD

**Issue by vic3lord** [fluxcd/image-automation-controller#167]
In Flux v1 we could just select latest image by a pattern + its image timestamp for example:

```
image: 'prod-*' # What comes after the '-' is the commit id
```

The image that was considered latest was the latest image by timestamp after filtered with prod-
Any known way to achieve this with Flux v2?

**Comment by kingdonb** [comment]
This is the related issue: https://github.com/fluxcd/flux2/discussions/802

> Deprecate "select latest by build time" for image automation

This means it is not possible. The recommended workflow is to change your image tagging strategy to something which can be sorted as a string, or with a string-sortable part, for reasons which are expressed more fully in the linked discussion.

https://fluxcd.io/docs/guides/sortable-image-tags/

It is known and documented that ImagePolicy is not strictly compatible with Flux v1 behavior.

If strict compatibility is absolutely required for your use case, this is addressed in https://fluxcd.io/docs/use-cases/gh-actions-manifest-generation/ where the concept of a compatibility shim that updates manifests from CI is discussed.

Skipping to the punchline: https://fluxcd.io/docs/use-cases/gh-actions-manifest-generation/#adapting-for-flux-v2

It is not recommended to use the compatibility shim, it is only provided as a temporary measure for example to facilitate a partial or strangler-pattern migration to Flux v2. Users are recommended to adopt the new requirements in ImagePolicy.

Please consider upgrading your image tags to use the sortable string tags, with a filter that sorts image tags by either build numbers, unix timestamps, or calver strings. `${branch}-${sha}-${ts}` is a good example that doesn't compromise too much.

**Comment by vic3lord** [comment]
Thanks @kingdonb, closing!
