### ISSUE TITLE
Observing flux unknown error: error: the key you are authenticating with has been marked as read only.

### ISSUE THREAD

**Issue by sairamvoggu1007** [fluxcd/image-automation-controller#208]
Hi Team,

Observing following error in image-automation-controller logs

> {"level":"error","ts":"2021-08-02T21:29:52.662Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","error":"unknown error: ERROR: The key you are authenticating with has been marked as read only."}

But the keys has proper access which worked earlier all of sudden started throwing above error

> {"level":"info","ts":"2021-08-02T19:04:14.208Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"pushed commit to origin","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","revision":"","branch":"environment"}

**Comment by hiddeco** [comment]
Can you please confirm that in your Git provider (e.g. GitHub, GitLab) the key wasn't accidentally marked as "ready-only" between `19:04:14.208` and `21:29:52.662`?

**Comment by demisx** [comment]
I am seeing the same error. Can you please clarify what key is being referred to here? I am using GitHub. Do you guys mean PAT (Personal Access Token)?

**Comment by demisx** [comment]
These are my current deploy keys which have been created by Flux bootstrap, I believe:

![Screen Shot 2021-09-03 at 1 32 10 PM](https://user-images.githubusercontent.com/4452412/132062775-b69fa98d-415c-4cc2-b9c2-e33d512eacda.gif)

**Comment by demisx** [comment]
I got this resolved by adding `--read-write-key` to the ` flux bootstrap github` command. This created a GitHub deploy read/write key, so flux is now able to update YAML and commit changes to GitHub. Not sure why it's missing from the docs https://fluxcd.io/docs/installation/#github-and-github-enterprise
