### ISSUE TITLE
Add ability to alert when a new image tag is deployed

### ISSUE THREAD

**Issue by hydradan** [fluxcd/image-automation-controller#227]
There currently doesn't appear to be a way for the notification controller to send an alert when a new image tag is applied to a `HelmRelease`. The `HelmRelease` alert contains the helm chart revision, but that's not particularly useful if the chart isn't being updated -- we'd also very much like the image tag to appear in the alert.

tl;dr How can send a note to our developers that contains the image tag whenever a new image is detected and applied to a helm release?

**Comment by stefanprodan** [comment]
I would label this as a bug, the image automation should not issue events for "no updates made".
