### ISSUE TITLE
Respect `paths` field in spec

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#24]
The ImageUpdateAutomationSpec includes a paths field, with the idea being that updates are only applied to files within the paths given.

**Comment by stevenklar** [comment]
Just want to make sure I understand this correctly.
Do you think this would solve the issue? @squaremo 

* Add function which does the same as **[updateAccordingToSetters](https://github.com/fluxcd/image-automation-controller/blob/fb26178744f678664f3de930c63ba51cffac8aac/controllers/imageupdateautomation_controller.go#L335)** but with additional **inpath** for **UpdateWithSetters** grabbed from ImageUpdateAutomationSpec
* And implement this optional path here:
https://github.com/fluxcd/image-automation-controller/blob/fb26178744f678664f3de930c63ba51cffac8aac/controllers/imageupdateautomation_controller.go#L133

Please correct me if I understood the issue wrong. :-)

**Comment by squaremo** [comment]
Just about -- the paths field is intended to take a list of paths below the git repo root. So you'd need to iterate over that list, joining the subpath onto the `tmp` directory, and apply update.UpdateWithSetters for each of them. You'd also need to remember to provide a default, when the field is missing.

**Comment by squaremo** [comment]
@stevenklar This would be a very welcome contribution, just to put some whuffies on the table :-)

**Comment by squaremo** [comment]
I've removed `paths` from the spec (#64), at least for a 0.1.0 release. I lobbed it in because I thought it would be useful, but it doesn't really have a problem that it's solving. Until we find one of those (a problem), I'll put this on ice.
