### ISSUE TITLE
Remove usage deprecated io/ioutil

### ISSUE THREAD

**Issue by makkes** [fluxcd/image-automation-controller#240]
This is supposed to track implementation of fluxcd/flux2#1658 in this repo.

**Comment by robotjellyzone** [comment]
Hi , I will try to work on this !

**Comment by robotjellyzone** [comment]
can you provide more info on this? also does this issue requires any kind of knowledge in flux?

**Comment by rishabh96b** [comment]
Hi, @robotjellyzone 
You don't need the flux knowledge for this issue. Just refer to https://github.com/fluxcd/flux2/issues/1658, there are other patches in different repositories addressing the similar issue.

**Comment by robotjellyzone** [comment]
Ok i will take this up then ! thanks for your reply !

**Comment by robotjellyzone** [comment]
can you assign me this

**Comment by rishabh96b** [comment]
You'll be assigned by one of the maintainers @robotjellyzone 🙂

**Comment by makkes** [comment]
@robotjellyzone you can take a look at https://github.com/fluxcd/kustomize-controller/pull/479 for an example of what's needed.

**Comment by stefanprodan** [comment]
Fixed in #267
