### ISSUE TITLE
Missing return statement after error

### ISSUE THREAD

**Issue by dholbach** [fluxcd/image-automation-controller#244]
From Ada Logics

> In the Image-automation reconciler an issue is present where the code continues after an error occurs, leading to undefined behaviour:

https://github.com/fluxcd/image-automation-controller/blob/674f833d982628831c101a919c0154c64c455db3/controllers/imageupdateautomation_controller.go#L204-L211

> The problem is that the `failWithError` branch does not itself return from the reconcile function and the code should instead be return `failWithError`

> Recommendation

> Change the code to return `failWithError`

**Comment by relu** [comment]
Fixed in https://github.com/fluxcd/image-automation-controller/commit/5a831a8a00a81c9ef268a22ba28e61158c22e339.
