### ISSUE TITLE
Unnecessary conditions in the code

### ISSUE THREAD

**Issue by dholbach** [fluxcd/image-automation-controller#245]
From Ada Logics

> In the following code, the `auto.Spec.Update` is not needed, and if indeed `auto.Spec.Update` was nil then the first conditional statement would be panic due to a nil-dereference.

https://github.com/fluxcd/image-automation-controller/blob/7ec4e6150ee0b6f4770a3265161cd98108c06603/controllers/imageupdateautomation_controller.go#L253-L264

> Recommendation
> Remove unnecessary code.

**Comment by Nalum** [comment]
I'd like to take up this issue if that's good with you
