### ISSUE TITLE
Possible nil-deref in image-automation controller

### ISSUE THREAD

**Issue by dholbach** [fluxcd/image-automation-controller#246]
From Ada Logics:

> Consider the following code:

https://github.com/fluxcd/image-automation-controller/blob/674f833d982628831c101a919c0154c64c455db3/controllers/imageupdateautomation_controller.go#L310-L320

> When the `lastTime.Format` is called it is not certain that `lastTime` is not a nil-pointer. As such, similar to a check on `lastCommit` there should be a check on whether `lastTime` is nil.

**Comment by Nalum** [comment]
I'd like to take up this issue if that's good with you

**Comment by Nalum** [comment]
At the moment there is no error message returned if `lastCommit` is an empty string, is this okay to stay this way or should there be an `else failWithError` at this point?

**Comment by Nalum** [comment]
If `lastCommit` is not an empty string but `lastTime` is `nil` do you still want `lastCommit` in `statusMessage`?

I feel like it's unlikely to happen that you would have one without the other but it is possible.

**Comment by hiddeco** [comment]
I feel the presence of both is required for the observation to be correct.
