### ISSUE TITLE
Set default observedGeneration to -1

### ISSUE THREAD

**Issue by makkes** [fluxcd/image-automation-controller#275]
This is a follow-up for the tracking issue fluxcd/flux2#2007.

The default observedGeneration has to be set on the following CRDs:

* ImageUpdateAutomation

**Comment by sbernheim** [comment]
@makkes - This seems pretty straightforward, and I have a commit ready to resolve it based on @tomhuang12 's previous PR. fluxcd/image-reflector-controller#189 (Thanks, Tom!)

I'd like to submit a PR for this Issue during @scottrigby 's Controller Collab session tomorrow to demonstrate the contribution process for first-timers, if that's OK.  I'll submit the PR tomorrow afternoon regardless if we don't get to it during the class.

You can ping me on the Weaveworks or CNCF Slack to let me know if you would prefer that I not this Issue as a `good-first-issue` classroom example.

**Comment by stefanprodan** [comment]
Fixed in #277
