### ISSUE TITLE
Support cross-namespace sourceRef in ImageUpdateAutomation

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#294]
For some deployments of Flux, the GitRepository object giving access to a git repo is owned by one team, and the definitions for image updates (ImageRepository, ImagePolicy, and ImageUpdateAutomation) are owned by other teams. There is a strong preference in those cases for keeping the GitRepository in one namespace, and letting teams define automation in their own namespaces -- but to be able to do that, the ImageUpdateAutomation object would need to be able to refer to a GitRepository object in another namespace.

Similar work was done in https://github.com/fluxcd/image-reflector-controller/pull/162, and for more background on similar use cases, see https://github.com/fluxcd/image-automation-controller/issues/85.

(I am not going to recapitulate the pros and cons of breaking namespace isolation here -- that ship has sailed <sup>[meaning](https://idioms.thefreedictionary.com/ship+has+sailed)</sup>.)

**Comment by aryan9600** [comment]
Looking at fluxcd/image-reflector-controller#162, do we want to add similar ACL support or let `ImageUpdateAutomation` objects in any namespace have access to a `GitRepository `?

**Comment by squaremo** [comment]
> do we want to add similar ACL support or let `ImageUpdateAutomation` objects in any namespace have access to a `GitRepository`?

Good question. I would feel more comfortable waiting for `accessFrom` to be implemented in source controller, then respecting it here.

**Comment by stefanprodan** [comment]
> Good question. I would feel more comfortable waiting for accessFrom to be implemented in source controller, then respecting it here.

ACLs are client-side, as described in https://github.com/fluxcd/flux2/pull/2092

**Comment by stefanprodan** [comment]
@squaremo according to https://github.com/fluxcd/flux2/pull/2093 this controller should accept cross-namespace refs as KC and HC do now. When that RFC is merged, only then we can add a flag to enforce ACLs.
