### ISSUE TITLE
image-automation-controller leaks git server connections

### ISSUE THREAD

**Issue by panumjp** [fluxcd/image-automation-controller#316]
I think this started after upgrade to 0.26.0. Current version is 0.26.3

$ flux check
► checking prerequisites
✔ Kubernetes 1.21.7 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 13:20:23 EET 2022
4
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 13:26:24 EET 2022
10
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 13:29:28 EET 2022
13
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 13:30:52 EET 2022
15
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 13:37:19 EET 2022
21
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 13:41:39 EET 2022
25
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 14:17:11 EET 2022
61
$ date ; kubectl exec -n flux-system image-automation-controller-675bff6646-nzjnh -- netstat -n | grep ESTABLISHED | grep .56.14:22 | wc -l
Fri Feb 11 14:24:56 EET 2022
68

$ kubectl logs -n flux-system image-automation-controller-675bff6646-nzjnh
{"level":"info","ts":"2022-02-11T11:19:41.420Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2022-02-11T11:19:41.421Z","logger":"setup","msg":"starting manager"}
{"level":"info","ts":"2022-02-11T11:19:41.421Z","msg":"Starting server","kind":"health probe","addr":"[::]:9440"}
{"level":"info","ts":"2022-02-11T11:19:41.421Z","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
I0211 11:19:41.523004       1 leaderelection.go:248] attempting to acquire leader lease flux-system/image-automation-controller-leader-election...
I0211 11:19:41.540928       1 leaderelection.go:258] successfully acquired lease flux-system/image-automation-controller-leader-election
{"level":"info","ts":"2022-02-11T11:19:41.541Z","logger":"controller.imageupdateautomation","msg":"Starting EventSource","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","source":"kind source: *v1beta1.ImageUpdateAutomation"}
{"level":"info","ts":"2022-02-11T11:19:41.541Z","logger":"controller.imageupdateautomation","msg":"Starting EventSource","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","source":"kind source: *v1beta1.GitRepository"}
{"level":"info","ts":"2022-02-11T11:19:41.541Z","logger":"controller.imageupdateautomation","msg":"Starting EventSource","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","source":"kind source: *v1beta1.ImagePolicy"}
{"level":"info","ts":"2022-02-11T11:19:41.541Z","logger":"controller.imageupdateautomation","msg":"Starting Controller","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation"}
{"level":"info","ts":"2022-02-11T11:19:41.642Z","logger":"controller.imageupdateautomation","msg":"Starting workers","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","worker count":4}

**Comment by pjbgf** [comment]
@panumjp thanks for reporting, I managed to reproduce this in both `image-automation-controller` and `source-controller`. 
Looking to provide a fix on this soon.

**Comment by pjbgf** [comment]
@panumjp I managed to reproduce two scenarios so far that yield connections and wanted to make sure yours fit into them. Would you be able to please share the information below? 

- Full `netstat` results: feel free to redact any sensitive IP addresses, but please leave the ports on.
- How many HelmRepositories and HelmCharts do you have in your cluster?
- Have you noticed the number of connections estabilise or decrease at some point?

**Comment by panumjp** [comment]
[netstat.txt](https://github.com/fluxcd/image-automation-controller/files/8066572/netstat.txt)

We have 18 helmrepositories and 18 helmcharts in this cluster.
Number of connections increases until our internal on-prem gitlab server hangs (will take days). No signs of stabilization or decrease of connections so far.

Number of connections increases in every minute (interval in ImageUpdateAutomation is set to 1m0s) with entries like this in log of image-automation-controller when log-level is set to debug:
```
{"level":"debug","ts":"2022-02-15T06:10:08.840Z","logger":"controller.imageupdateautomation","msg":"fetching git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"}}
{"level":"debug","ts":"2022-02-15T06:10:08.840Z","logger":"controller.imageupdateautomation","msg":"attempting to clone git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"},"ref":{"branch":"master"},"working":"/tmp/flux-system-flux-system3035407245"}
{"level":"debug","ts":"2022-02-15T06:10:09.863Z","logger":"controller.imageupdateautomation","msg":"updating with setters according to image policies","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","count":22,"manifests-path":"/tmp/flux-system-flux-system3035407245"}
{"level":"debug","ts":"2022-02-15T06:10:09.870Z","logger":"controller.imageupdateautomation","msg":"ran updates to working dir","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","working":"/tmp/flux-system-flux-system3035407245"}
{"level":"debug","ts":"2022-02-15T06:10:09.895Z","logger":"controller.imageupdateautomation","msg":"no changes made in working directory; no commit","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system"}
{"level":"debug","ts":"2022-02-15T06:11:09.923Z","logger":"controller.imageupdateautomation","msg":"fetching git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"}}
{"level":"debug","ts":"2022-02-15T06:11:09.923Z","logger":"controller.imageupdateautomation","msg":"attempting to clone git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"},"ref":{"branch":"master"},"working":"/tmp/flux-system-flux-system2157400672"}
{"level":"debug","ts":"2022-02-15T06:11:10.989Z","logger":"controller.imageupdateautomation","msg":"updating with setters according to image policies","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","count":22,"manifests-path":"/tmp/flux-system-flux-system2157400672"}
{"level":"debug","ts":"2022-02-15T06:11:10.994Z","logger":"controller.imageupdateautomation","msg":"ran updates to working dir","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","working":"/tmp/flux-system-flux-system2157400672"}
{"level":"debug","ts":"2022-02-15T06:11:11.021Z","logger":"controller.imageupdateautomation","msg":"no changes made in working directory; no commit","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system"}
{"level":"debug","ts":"2022-02-15T06:12:11.050Z","logger":"controller.imageupdateautomation","msg":"fetching git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"}}
{"level":"debug","ts":"2022-02-15T06:12:11.050Z","logger":"controller.imageupdateautomation","msg":"attempting to clone git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"},"ref":{"branch":"master"},"working":"/tmp/flux-system-flux-system16674011"}
{"level":"debug","ts":"2022-02-15T06:12:12.141Z","logger":"controller.imageupdateautomation","msg":"updating with setters according to image policies","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","count":22,"manifests-path":"/tmp/flux-system-flux-system16674011"}
{"level":"debug","ts":"2022-02-15T06:12:12.146Z","logger":"controller.imageupdateautomation","msg":"ran updates to working dir","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","working":"/tmp/flux-system-flux-system16674011"}
{"level":"debug","ts":"2022-02-15T06:12:12.181Z","logger":"controller.imageupdateautomation","msg":"no changes made in working directory; no commit","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system"}
{"level":"debug","ts":"2022-02-15T06:13:12.215Z","logger":"controller.imageupdateautomation","msg":"fetching git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"}}
{"level":"debug","ts":"2022-02-15T06:13:12.215Z","logger":"controller.imageupdateautomation","msg":"attempting to clone git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"},"ref":{"branch":"master"},"working":"/tmp/flux-system-flux-system1201257356"}
{"level":"debug","ts":"2022-02-15T06:13:13.167Z","logger":"controller.imageupdateautomation","msg":"updating with setters according to image policies","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","count":22,"manifests-path":"/tmp/flux-system-flux-system1201257356"}
{"level":"debug","ts":"2022-02-15T06:13:13.172Z","logger":"controller.imageupdateautomation","msg":"ran updates to working dir","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","working":"/tmp/flux-system-flux-system1201257356"}
{"level":"debug","ts":"2022-02-15T06:13:13.200Z","logger":"controller.imageupdateautomation","msg":"no changes made in working directory; no commit","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system"}
{"level":"debug","ts":"2022-02-15T06:14:13.224Z","logger":"controller.imageupdateautomation","msg":"fetching git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"}}
{"level":"debug","ts":"2022-02-15T06:14:13.224Z","logger":"controller.imageupdateautomation","msg":"attempting to clone git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"},"ref":{"branch":"master"},"working":"/tmp/flux-system-flux-system1202811354"}
{"level":"debug","ts":"2022-02-15T06:14:14.176Z","logger":"controller.imageupdateautomation","msg":"updating with setters according to image policies","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","count":22,"manifests-path":"/tmp/flux-system-flux-system1202811354"}
{"level":"debug","ts":"2022-02-15T06:14:14.181Z","logger":"controller.imageupdateautomation","msg":"ran updates to working dir","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","working":"/tmp/flux-system-flux-system1202811354"}
{"level":"debug","ts":"2022-02-15T06:14:14.205Z","logger":"controller.imageupdateautomation","msg":"no changes made in working directory; no commit","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system"}
```

**Comment by mycrEEpy** [comment]
We see the same on our infrastructure.
The GitSource is configured with SSH and we see increasing number of open connections on our SSH load balancer.

**Comment by aryan9600** [comment]
@mycrEEpy @panumjp do you mind testing this image:  `quay.io/aryan9600/iac:a348d9f3` and check if that fixes this issue? 

```
docker pull quay.io/aryan9600/iac:a348d9f3
docker tag quay.io/aryan9600/iac:a348d9f3 ghcr.io/fluxcd/image-automation-controller:v0.20.0
kubectl scale -n flux-system deployment image-automation-controller --replicas=0
kind load docker-image ghcr.io/fluxcd/image-automation-controller:v0.20.0
kubectl scale -n flux-system deployment image-automation-controller --replicas=1
```

**Comment by ambis** [comment]
No, we will not run a blackbox image in our systems. We have no clue what runs in that image. (I'm a collegue of panumjp's).

**Comment by aryan9600** [comment]
That's understandable. If you'd still be willing to help confirm the fix, you could checkout to commit https://github.com/fluxcd/image-automation-controller/commit/a348d9f3, build the image and test that:
`docker buildx build --platform=<> --load .`

**Comment by mycrEEpy** [comment]
@aryan9600 We build the image and testing right now. Will give an update in a few minutes/hours.

**Comment by mycrEEpy** [comment]
@aryan9600 In our setup the image-automation-controller does not leak any connections with your changes. :+1:

**Comment by uberspot** [comment]
Tested the image as well and it looks better. Can we please merge that fix? The git connection leak is seriously impacting our infrastructure.

**Comment by darkowlzz** [comment]
Hi, the fix is available in flux [v0.27.3](https://github.com/fluxcd/flux2/releases/tag/v0.27.3).
Please update and give it a try.

**Comment by panumjp** [comment]
looks like v0.27.3 works as expected!
thanks to everyone involved for fixing the bug and doing the tests

**Comment by hiddeco** [comment]
Given we have two individual confirmations now, I am going to close this issue. If for some reason it does _not_ work for you, please shout and I'll press the magic button to re-open. :bow:
