### ISSUE TITLE
replace variable in imagepolicy marker line

### ISSUE THREAD

**Issue by rafaelperoco** [fluxcd/image-automation-controller#344]
I'm creating templates for my helmreleases and everything is working fine using postBuild but, because imagepolicy marker is inside a comment, postBuild can't change the value of it.

You have any suggestions how to do it work?

**Comment by kingdonb** [comment]
I'm not sure what you tried exactly, but I'm sorry you're having difficulty with this!

The ImagePolicy marker must be placed in a comment alongside of a `key: value` pair and postBuild shouldn't have to set the value of it.

If you have a patch or kustomize overlay for each environment, you can put the imagepolicy marker there like in:
https://fluxcd.io/docs/guides/image-update/#configure-image-updates

The key is, ImageUpdateAutomation does not look at the resources in the cluster, it writes changes directly to the file where the ImagePolicy marker is placed in Git. So it is not something you can use in postBuild, where certain resources depending on which environment they use, and what base they inherited the Kustomization through, get different policies.

The Image Update must locate the comment next to the value to replace, in a YAML file which should not be templated (but can be used downstream in later templates, like for example, in a configmap or values.yaml for Helm chart)

Hope that this information helps!
