### ISSUE TITLE
Image updates not happening

### ISSUE THREAD

**Issue by thulasidassrinivasan** [fluxcd/image-automation-controller#357]
Hi team, 
I followed the document https://fluxcd.io/docs/guides/image-update/ and configured the things as stated however new image updates are not happening even though i have latest image

Kubernetes: AKS
Version:1.22.6
ImageRepository: ACR

Authentication from AKS to ACR is via docker secret created in AKS and same is configured to be used in ImageRepository.

```---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Automated image update
        Automation name: {{ .AutomationObject }}
        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}
        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}
        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}} 
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/aks/aaaa
    strategy: Setters
```
Image policy
```apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: staging-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: acr
  policy:
    semver:
      range: '>=2.4.0'
```

Registry
```---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: acr.azurecr.io/aks/aaaa
  interval: 1m0s
  secretRef:
    name: 'acr-secret
```

Please help on why i do not see any changes happening even though all seems correct. What I am missing here ?

**Comment by thulasidassrinivasan** [comment]
@pjbgf - Could you please help ?

**Comment by pjbgf** [comment]
@thulasidassrinivasan would you mind dialling up the trace so we can get more information about the reconciliations?
What are you getting when you run:

```
flux get images all
```

**Comment by thulasidassrinivasan** [comment]
@pjbgf - Thanks for checking. I get no output when i run the command `flux get images all`

**Comment by pjbgf** [comment]
`flux get images all` should return all the image related flux objects you have in the namespace `flux-system`. 
If you have created your image objects in another namespace you will have to specify it by using `-n <namespace>`.

**Comment by thulasidassrinivasan** [comment]
@pjbgf  - I have created image objects inside flux-system namespaces only. I am sure I am missing something that the flux system not understanding about the images. strange thing is no error message also.

**Comment by pjbgf** [comment]
@thulasidassrinivasan given that you are getting anything out of `flux get images all`, sounds like `ImageUpdateAutomation`, `ImagePolicy` and `ImageRepository` are not present in the `flux-system` namespace.

Can you please try `flux get images all -A` and see whether they are found anywhere else within the cluster?
Also, to get more information about the controller, more detailed reconciling logs, you can dial up the log level with `--log-level=debug` in the arguments of your controller.

**Comment by thulasidassrinivasan** [comment]
@pjbgf Thanks for helping. I was digging deep and i found that imagerepository was not working as expected because of misconfiguration from my side. I corrected it and all looks superb now. 👍 💯

**Comment by pjbgf** [comment]
Excellent news @thulasidassrinivasan, I am happy that is now resolved. 

I'm closing the issue, but feel free to reach out on Flux's CNCF Slack or via a new issue in case you need more help. :+1:
