### ISSUE TITLE
Image Policy not in same ns as image update automation are ignored

### ISSUE THREAD

**Issue by Frizlab** [fluxcd/image-automation-controller#361]
Setup:
- In the `flux-system` repo, I have an image update automation, and an image repository;
- In another ns (let’s say `myapp`), I have an image policy;
- I added the following annotation on some of yaml files in the repo: `# {"$imagepolicy": "myapp:mypolicy"}`.

The annotation is discovered by the image automation controller (I read the automation controller logs in trace mode), but it does not update the yaml.

If I move the image policy to the `flux-system` ns (and I update the annotation accordingly), it works.

Additionally, note I did not get any info on what was going on.
Just a vague `updating with setters according to image policies` log, but nothing told me the setter was not found, or anything else.

**Comment by kingdonb** [comment]
I wonder if you have set `--no-cross-namespace-refs=true` according to the [bootstrap cheatsheet](https://fluxcd.io/docs/cheatsheets/bootstrap/#multi-tenancy-lockdown)? It seems if that was the case, and it was blocking this, then you would find a hint about it in the `image-automation-controller` logs.

If not, then cross-namespace references should be allowed, but you might have missed that you need to include the namespace of the `GitRepository` in the source ref, if the GitRepository is in a different namespace than the ImageUpdateAutomation. Can you check these and let us know if that's the issue?

**Comment by kingdonb** [comment]
I found a different thread where it's made clear, yes. I think the ImageUpdateAutomation still has to be in the same namespace as the ImagePolicy. This wasn't clear to me until I read this thread: https://github.com/fluxcd/flux2/discussions/2702

**Comment by Frizlab** [comment]
Ha! Good to know. I wonder why…
Anyway, I’m closing this issue as it seem to be working as expected.
