### ISSUE TITLE
unable to fetch remote '<gitlab-project-url>': Unhandled HTTP error 422 Unprocessable Entity with v0.23.0

### ISSUE THREAD

**Issue by sisid-github** [fluxcd/image-automation-controller#379]
Hi,

I encountered an issue running the image-automation-controller v0.23.0 after the flux v0.31.0 update.

#### Flux info
```
flux: v0.31.0
helm-controller: v0.22.0
image-automation-controller: v0.23.0
image-reflector-controller: v0.19.0
kustomize-controller: v0.26.0
notification-controller: v0.24.0
source-controller: v0.25.3
```

I am bootstrapping using a private Gitlab repo
 
#### Issue
After the update, the image automation controller (v0.23.0) showed the following error: 
`unable to fetch remote '<gitlab-project-url>': Unhandled HTTP error 422 Unprocessable Entity`

Reverting to previous Flux version fixes the issue (as image-automation-controller is reverted to v0.22.1)

#### Fix / analysis
After digging a while, I manage to fix the issue simply by adding ".git" to my GitRepository URL while running v0.23.0

My url looked like this: `https://gitlabhost.com/group/fluxcd`, changed it to `https://gitlabhost.com/group/fluxcd.git` to fix the issue.

Note that [Flux documentation](https://fluxcd.io/docs/components/source/gitrepositories/#example) does not include the ".git" extension, although there is nothing specific regarding Gitlab. Not sure the issue is specific to Gitlab or also applies to Github repo.

**Comment by pjbgf** [comment]
@sisid-github thank you for reporting this, we are working on a fix for this and will let you know once you have more information.

**Comment by pjbgf** [comment]
@sisid-github the fix is now merged onto source controller and soon it will make its way to image automation controller.

We should release new docker images for both Today.
