### ISSUE TITLE
Too many ssh connection 

### ISSUE THREAD

**Issue by ywyt738** [fluxcd/image-automation-controller#390]
```bash
netstat -lnatp | grep -i establish | grep :22 | wc -l
```
The connection will increase infinity.

version: ghcr.io/fluxcd/image-automation-controller:v0.23.2

**Comment by pjbgf** [comment]
@ywyt738 thank you for reporting this issue. This is related to #334 and we have recently created a release candidate with a fix:

`ghcr.io/fluxcd/image-automation-controller:rc-843074dd`

The next patch (v0.23.3) should be released Tomorrow with this fix.

**Comment by pjbgf** [comment]
Closing this issue as the fix has been released on [v0.23.4](https://github.com/fluxcd/image-automation-controller/releases/tag/v0.23.4).
