### ISSUE TITLE
Send events to notifier for successful automated commits

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-automation-controller#46]
GOTK has a notification-controller which can be used to forward events from the controllers to external systems, e.g., Slack, or webhooks. The automation controller has an event which is worthy of a notification, which is when it's successfully made a commit.

**Comment by stefanprodan** [comment]
Any error encountered during the git clone or push operations should also be pushed as an event.

**Comment by squaremo** [comment]
#47 sends an event on success, with a revision in the message, and for the various failures; #60 extends these events to the ExternalEventRecorder (i.e., to the notification controller).
