### ISSUE TITLE
ImageUpdateAutomation  "object not found" when using single repo across multiple clusters.

### ISSUE THREAD

**Issue by PaulSxxxs** [fluxcd/image-automation-controller#591]
I'm having this same issue as https://github.com/fluxcd/image-automation-controller/issues/498 and i am trying to disable GitShallowClone. However i'm unsure how to build the image with `--feature-gates=GitShallowClone=false`, Can someone provide some guidance to try this?

This seems similar to https://github.com/fluxcd/image-automation-controller/issues/164
 and https://github.com/fluxcd/image-automation-controller/issues/498 

_Originally posted by @PaulSxxxs in https://github.com/fluxcd/image-automation-controller/issues/498#issuecomment-1726766858_

**Comment by hiddeco** [comment]
You need to patch the image-automation-controller Deployment to include the `--feature-gates=GitShallowClone=false` argument.

More information around customizing Flux instances can be found here: https://fluxcd.io/flux/installation/configuration/boostrap-customization/

**Comment by PaulSxxxs** [comment]
Thanks! I managed to figure out how to patch and the feature gate is applied, but my issue hasn't gone away
