### ISSUE TITLE
Status shows "no updates made"

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/image-automation-controller#69]
Even if the automation runs fine and commits are being pushed to Git, the status show "no updates made".

**Comment by stefanprodan** [comment]
I never seen “committed and pushed” while writing/testing the guide. Anyway I think the status should reflect the last push, otherwise I see no value in having a status, it’s just confusing.

**Comment by squaremo** [comment]
> I think the status should reflect the last push, otherwise I see no value in having a status, it’s just confusing.

The status can certainly make reference to the last commit pushed. With respect to the ready condition specifically, it's arguable I think -- the condition usually reflects the reason to consider it up to date, in the spirit of e.g., a deployment reporting that all its pods are OK. (The argument on the other side is a condition should report what prompted its last transition -- but then, _new_ commits would not be reported if it was already ready. Ho hum.)

I would expect there to be a window of `.spec.interval` where the ready condition has a "commit pushed" message before it tries again and changes the message -- if you never saw that, perhaps something else is going on.

**Comment by stefanprodan** [comment]
Maybe we could say something like "no changes made, last pushed <SHORT-SHA> at <TS>` this way, users can tell what's going on.

**Comment by squaremo** [comment]
> Maybe we could say something like `no changes made, last pushed <SHORT-SHA> at <TS>` this way, users can tell what's going on.

Yeah that's a decent suggestion :+1: Adding a field with exactly the last commit might also be useful, I'll look into that too.
