### ISSUE TITLE
GitRepository branch is ignored

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/image-automation-controller#70]
If no branch is specified in the image automation object, instead of using the branch set in the referenced GitRepository, the controller uses `master` and this breaks the push. We should make the branch required or use the one specified in the GitRepository.

**Comment by squaremo** [comment]
A GitRepository doesn't always have a branch. Rather than come up with a scheme to handle other kinds of ref, I would rather make the branch mandatory in ImageUpdateAutomation.

**Comment by stefanprodan** [comment]
Fixed in #74
