### ISSUE TITLE
Support for OCIRepository as trigger for ImageUpdateAutomation

### ISSUE THREAD

**Issue by antonosmond** [fluxcd/image-automation-controller#725]
Currently to trigger updates, the `ImageUpdateAutomation` requires a `ImagePolicy` which requires a `ImageRepository`.
However, if I already have an `OCIRepository`, this includes a ref which can be used to filter the OCI artifacts e.g. using a semver constraint. This makes the `OCIRepository` a bit like an `ImageRepository` & `ImagePolicy` in one.
Given the `OCIRepository` is resolving the tag to use based on the given ref, it'd be nice if we could use this to drive an `ImageUpdateAutomation`. The result would be the same as with the `ImagePolicy` resources but instead of the tag coming from the `ImagePolicy` the tag would come from the `OCIRepository`.

**Comment by stefanprodan** [comment]
An `OCIRepository` pulls the image from the registry and extracts its content into the Flux artifact storage, using this for app containers would result in GB of traffic and massive storage costs.

**Comment by antonosmond** [comment]
Ah fair enough then I guess I'll stick to using `ImageRepository` resources for OCI rather than `OCIRepository` resources then.
