### ISSUE TITLE
Errors from ImageUpdateAutomation are not triggering a Discord alert

### ISSUE THREAD

**Issue by TrueBrain** [fluxcd/image-automation-controller#86]
I was fiddling with image automation a bit, and I managed to hit this error:

`{"level":"error","ts":"2021-01-13T15:57:20.289Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"image.toolkit.fluxcd.io","reconcilerKind":"ImageUpdateAutomation","controller":"imageupdateautomation","name":"flux-system","namespace":"flux-system","error":"unknown error: ERROR: The key you are authenticating with has been marked as read only."}`

Which totally makes sense, as the GitHub key I use is set to read-only.

What I did notice how-ever, is that this error is not shown to me on Discord, with an unmodified flux2 setup via Kustomize (configured to display errors on Discord). I would have expected this error to end up there, as most other errors flux2 generates does.

When I looked further into this, I noticed that `eventSources` of `Alert` did not read `ImageUpdateAutomation` yet, but .. this is also not supported (yet?).

**Comment by squaremo** [comment]
> When I looked further into this, I noticed that `eventSources` of `Alert` did not read `ImageUpdateAutomation` yet, but .. this is also not supported (yet?).

From a quick read, I think the notification controller will process any kind that is sent its way. But the CRD will only accept (from amongst the image types) ImageRepository -- I've filed https://github.com/fluxcd/notification-controller/pull/128.

**Comment by squaremo** [comment]
fluxcd/notification-controller#128 was merged, so I think this will be fixed in an upcoming release.

**Comment by squaremo** [comment]
(Close in anticipation -- if you try again with a new release and find it still doesn't work, please reopen!)
